apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guitartortona-vue
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: guitar-ca-issuer
    nginx.ingress.kubernetes.io/limit-rps: "100"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - vue-staging.guitar.lab
      secretName: guitar-wildcard-tls
  rules:
    - host: vue-staging.guitar.lab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: guitartortona-vue
                port:
                  number: 8080