apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vue-staging

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
  - external-secret-ghcr.yaml

patches:
  - path: deployment-patch.yaml

images:
  - name: ghcr.io/mmzitarosa/guitartortona-vue
    newTag: v1.0.0-rc1