apiVersion: apps/v1
kind: Deployment
metadata:
  name: guitartortona-web
  labels:
    environment: production
    app.kubernetes.io/version: v1.0.0
spec:
  template:
    metadata:
      labels:
        environment: production
        app.kubernetes.io/version: v1.0.0
    spec:
      containers:
        - name: guitartortona-web
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"