apiVersion: v1
kind: Service
metadata:
  name: guitartortona-web
  labels:
    app.kubernetes.io/name: guitartortona-web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: guitartortona-web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP