apiVersion: v1
kind: Service
metadata:
  name: guitartortona-vue
  labels:
    app.kubernetes.io/name: guitartortona-vue
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: guitartortona-vue
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP